<?php

namespace Database\Factories;

use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\User>
 */
class UserFactory extends Factory
{
    /**
     * The current password being used by the factory.
     */
    protected static ?string $password;

    public function definition(): array
    {
        $first_names = [
            'Aaron',
            'Adrianne',
            'Ajay',
            'Alexis Diggory',
            'Alexis Joseph Ralph',
            'Aljon',
            'Amalhaya',
            'Andrew James',
            'Angelica',
            'Angelito',
            'Anna Katrina',
            'Anthony James',
            'April Christian',
            'Archie',
            'Archiebal',
            'Beverly',
            'Brando Bonifacio',
            'Bryan Eduard',
            'Bryan',
            'Carlo',
            'Carmina',
            'Charles Vincent',
            'Charlotte',
            'Chester',
            'Chevy',
            'Christian Paul',
            'Christian',
            'Creasha Mae',
            'Crystallene Airra',
            'Czar Ember',
            'Daniel',
            'Danielle Mark',
            'Darren Bryle',
            'Daryl',
            'Dave Steven',
            'David Jan',
            'Dazen Jenie',
            'Delfin',
            'Drexler Jones',
            'Eddiebert',
            'Elmer Jay',
            'Eugene Rumel',
            'Faith Claire',
            'Francis Javier',
            'Geneva',
            'Geocelle Leonard',
            'Glenn',
            'Iris',
            'James',
            'Janmar',
            'Jaryl',
            'Jayrard',
            'Jayson',
            'Jeanne Kevin Arnmani',
            'Jecco',
            'Jeffrey',
            'Jeffrey',
            'Jeoffrei',
            'Jessica',
            'Jezreel',
            'Jhenny Rose',
            'Jhona Rhea',
            'John Carlo',
            'John Glenn',
            'John Jezreel',
            'John Marty',
            'John Paul',
            'Johnfrey',
            'Jomar',
            'Jomhar',
            'Jon Ruzzel',
            'Jose Junior',
            'Josephjoe',
            'Joven',
            'Jowel',
            'Joyce',
            'Judith',
            'Jule',
            'Kert Joshua',
            'Kevin Glenn',
            'Kevin Ricardo',
            'Kevin',
            'Klide',
            'Kristelle',
            'Kristoffer John Alfred',
            'Laika',
            'Lea',
            'Leilani',
            'Lennon',
            'Letecia',
            'Love Lyn',
            'Lyka',
            'Maria Victoria',
            'Maricon Terese',
            'Marifi',
            'Mark Anthony',
            'Mark Arnold',
            'Mark Jason',
            'Mark Lester',
            'Marla Ley',
            'Marvin Bravo',
            'Melody',
            'Merry Jean',
            'Michael Patrick',
            'Michael Russel',
            'Michael',
            'Michelle',
            'Mila Rose',
            'Monaliza',
            'Nicholson',
            'Nicole Alyza',
            'Noel',
            'Paolo Brylle',
            'Pauline',
            'Rachelle Grayce',
            'Ray Anthony',
            'Ricardo Jr.',
            'Richard',
            'Rocky',
            'Rodman',
            'Ronel',
            'Rose Marianne',
            'Ryan',
            'Shaira Lyn',
            'Suzerain Ezra',
            'Terrence',
            'Therese Bianca',
            'Tiffany Blanche',
            'Trojan Benedique',
            'Warren John',
            'Wilmark',
            'Zaldy',
            'Zarahnie'
        ];

        $maiden_names = [
            'Abalos',
            'Alca',
            'Amansec',
            'Amistad',
            'Anis',
            'Antonio',
            'Areola',
            'Austria',
            'Avilles',
            'Baday',
            'Balanta',
            'Balarbar',
            'Baliang',
            'Bandao',
            'Baptista',
            'Basbas',
            'Bravo',
            'Cachapero',
            'Calayaan',
            'Calip',
            'Carag',
            'Caragay',
            'Carbonell',
            'Carpio',
            'Casirayan',
            'Castillo',
            'Castro',
            'Chevy',
            'Ciriaco',
            'Corpuz',
            'Cruz',
            'Dacuyan',
            'Dalit',
            'Damo',
            'De Guzman',
            'De Jesus',
            'Dela Cruz',
            'Delos Reyes',
            'Diciembre',
            'Dogwe',
            'Domawa',
            'Domling',
            'Eduard',
            'Espinoza',
            'Estrada',
            'Fabia',
            'Fernandez',
            'Foyagan',
            'Gagarin',
            'Gangan',
            'Garcia',
            'Gaspar',
            'Gellecanao',
            'Gomeyac',
            'Ilarde',
            'Impian',
            'Jesus',
            'Juquiana',
            'Kitong',
            'Lacaden',
            'Langaoan',
            'Lapon',
            'Licupa',
            'Liwan',
            'Lomboy',
            'Lorenzo',
            'Lozano',
            'Lucero',
            'Madrid',
            'Magante',
            'Mangat',
            'Manuel',
            'Mendoza',
            'Morallos',
            'Ogoy',
            'Olida',
            'Oliver',
            'Orallo',
            'Ottao',
            'Pajota',
            'Palsario',
            'Pancubila',
            'Paningbatan',
            'Paragas',
            'Parco',
            'Pascua',
            'Payapaya',
            'Pedrito',
            'Pena',
            'Pig-ang',
            'Piguro',
            'Pili',
            'Pineda',
            'Piong',
            'Pleno',
            'Pumahing',
            'Quimson',
            'Ramos',
            'Regines',
            'Reyes',
            'Rosario',
            'Saltin',
            'Sanchez',
            'Santos',
            'Seraspe',
            'Singol',
            'Soria',
            'Suarez',
            'Talabis',
            'Tancio',
            'Tibayan',
            'Tinapngan',
            'Victor',
            'Vitales',
            'Yasin'
        ];

        $last_names = [
            'Abad',
            'Abrera',
            'Agoo',
            'Alamada',
            'Amansec',
            'Antiquera',
            'Apalla',
            'Aquino',
            'Arguelles',
            'Arimao',
            'Bajo',
            'Balanta',
            'Balonglong',
            'Banhaon',
            'Bastian',
            'Binan',
            'Boado',
            'Bola-oy',
            'Boladas',
            'Bombase',
            'Borja',
            'Cacanindin',
            'Cantor',
            'Caoili',
            'Carias',
            'Casasos',
            'Castillo',
            'Castro',
            'Caytap',
            'Claveria',
            'Consul',
            'Dagson',
            'Dasoy',
            'Datuin',
            'De Castro',
            'De Guzman',
            'Decena',
            'Del Castillo',
            'Duran',
            'Egmalis',
            'Estacio',
            'Estigoy',
            'Estrella',
            'Fabinal',
            'Fernandez',
            'Flores',
            'Galleo',
            'Garcia',
            'Garlejo',
            'Geminiano',
            'Genaro',
            'Gomia',
            'Gonzaga',
            'Gumapos',
            'Ituriaga',
            'Jacinto',
            'Jaravata',
            'Jovellanos',
            'Jularbal',
            'Labarda',
            'Lachica',
            'Lag-ey',
            'Laguardia',
            'Lapnawan',
            'Layson',
            'Long',
            'Lopez',
            'Lubin',
            'Lumbab',
            'Manuyag',
            'Marimat',
            'Marrero',
            'Martin',
            'Maurera',
            'Mina',
            'Mitchell',
            'Montilla',
            'Navarro',
            'Numbar',
            'Nuynuyan',
            'Oleta',
            'Oligario',
            'Ordinario',
            'Padilla',
            'Padua',
            'Palado',
            'Pangan',
            'Pangsiw',
            'Patulan',
            'Peningeo',
            'Perez',
            'Pila',
            'Ponseca',
            'Quillopa',
            'Ramirez',
            'Rimorin',
            'Robles',
            'Roxas',
            'Saclag',
            'Sadio',
            'Safoket',
            'Salio',
            'Samson',
            'Sanchez',
            'Sebio',
            'Sepada',
            'Soriano',
            'Sunga',
            'Tabao-ican',
            'Tam',
            'Tan',
            'Tesorio',
            'Tinio',
            'Torio',
            'Uson',
            'Veloso',
            'Villanueva',
            'Villaruz'
        ];

        $first_name = fake()->randomElement($first_names);
        $maiden_name = fake()->randomElement($maiden_names);
        $last_name = fake()->randomElement($last_names);

        $has_user = User::where('first_name', $first_name)->first();
        do {
            $first_name = fake()->randomElement($first_names);
            $has_user = User::where('first_name', $first_name)->first();
        } while ($has_user);

        return [
            'first_name' => $first_name,
            'maiden_name' => $maiden_name,
            'last_name' => $last_name,
            'email' => 'chatsmithonline.' .str_replace(' ', '', strtolower(trim($first_name))). '@example.com',
            'username' => str_replace(['\'', ' '], '', strtolower(trim($last_name. $first_name))). $this->faker->numberBetween(1, 99),
            'phone_number' => fake()->numerify('+639#########'),
            'address' => fake()->address(),
            'profile_photo_path' => null,
            'password' => static::$password ??= Hash::make('cos12345'),
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null,
            'remember_token' => Str::random(10),
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     */
    public function unverified(): static
    {
        return $this->state(fn (array $attributes) => [
            'email_verified_at' => null,
        ]);
    }
}
